name: Test contracts in audit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main
      - beber89/manual 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install
        continue-on-error: false

      - name: Run tests
        shell: bash
        run: npx hardhat test test/Lock.ts 
        continue-on-error: false